---
- hosts: all
#  become: true
  gather_facts: no
  vars:
     - user: ansible
  roles:
 #    - role: common
 #    - role: user
 #    - role: docker
 #    - role: git
     - role: python
     - role: pip
     - role: deployapp
