---
      - name: User Creation Playbook - Create a login user
        user:
          name: "{{ user }}"
          group: 
             - wheel
             - docker
             - root
          append: yes
          createhome: yes        # Defaults to yes
          home: /home/ansible    # Defaults to /home/<username>
          state: present
          generate_ssh_key: yes
          ssh_key_type: rsa
          ssh_key_file: "~/.ssh/id_rsa.pub"

      - name: User Creation Playbook - Add public key to authorized_keys
        authorized_key:
          user: "{{ user }}"
          state: present
          key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    #  - name: User Creation Playbook - Add {{ user }} to sudoers file
    #    ansible.builtin.lineinfile:
    #      path: /etc/sudoers
    #      state: present
    #      regexp: '^{{ user }}'
    #      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    #      validate: 'visudo -cf %s'
    
      - name: User Creation Playbook - Add user "{{ user }}" to sudo
        lineinfile:
          path: /etc/sudoers.d/"{{ user }}"
          line: '"{{ user }}" ALL=(ALL:ALL) NOPASSWD: ALL'
          state: present
          mode: 0440
          create: yes
          validate: 'visudo -cf %s'
