---
- name: ensure a list of packages installed
  command: yum groupinstall "Development Tools"
#    name: "{{ packages }}"
#  vars:
#    packages:
#      - gcc
#      - openssl-devel
#      - bzip2-devel
#      - libffi-devel
  become: yes
