---
- name: ensure a list of packages installed
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
  become: yes
