---
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  dnf:
    packages:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
  become: yes
