---
#    - name: Clone a github repository
#      become: yes
#      git:
#        repo: https://github.com/dstanbeca/academyapp.git
#        dest: /home/ansible/repos/
#        clone: yes
#       version: main
#        force: yes
#        update: yes
    - name: Start ssh-agent
      command: eval "$(ssh-agent -s)"
      
    - name: Clone a private repository.
      git:
        repo: git@github.com:dstanbeca/academyapp.git
        version: main
        dest: /home/ansible/reposs/
        accept_hostkey: yes
        key_file: /home/ansible/.ssh/id_ed25519
        clone: yes
        update: yes
#      become: yes
#      become_user: "{{ user }}"
        
    - name: Stop Docker Compose Stack running
      command: chdir=/home/ansible/repos/ docker compose down
      
    - name: Deploy Docker Compose stack
      command: chdir=/home/ansible/repos/ docker compose up -d
