---
    - name: Clone a github repository
      git:
        repo: https://github.com/dstanbeca/academyrepoansible.git
        dest: /home/ansible/repos/
        clone: yes
        update: yes
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /home/ansible/repos/
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/ansible/repos/
      register: output

    - ansible.builtin.debug:
        var: output
