---
    - name: Clone a github repository
      become: yes
      git:
        repo: https://github.com/dstanbeca/academyapp.git
        dest: /home/ansible/repos/
        clone: yes
        update: yes
        
    - name: Change directory
      command: cd /home/ansible/repos/
      
    - name: Deploy Docker Compose stack
      command: chdir=/home/ansible/repos/ docker compose up -d
