---
    - name: Clone a github repository
      git:
        repo: https://github.com/dstanbeca/academyapp.git
        dest: /home/ansible/repos/
        clone: yes
        update: yes
    - name: Tear down existing services
      docker_compose:
        project_src: /home/ansible/repos/
        state: absent

    - name: Create and start services
      docker_compose::
        project_src: /home/ansible/repos/
      register: output
