---
#    - name: Clone a github repository
#      become: yes
#      git:
#        repo: https://github.com/dstanbeca/academyapp.git
#        dest: /home/ansible/repos/
#        clone: yes
#       version: main
#        force: yes
#        update: yes

    - name: Clone a private repository.
      git:
        repo: git@github.com:dstanbeca/academyapp.git
        version: main
        dest: /home/ansible/repos/
        accept_hostkey: yes
        clone: yes
        update: yes
      become: yes
#      become_user: "{{ user }}"
        
    - name: Check if containers are running
      command: chdir=/home/ansible/repos/ docker compose down
      
    - name: Deploy Docker Compose stack
      command: chdir=/home/ansible/repos/ docker compose up -d
