---
#    - name: Clone a github repository
#      become: yes
#      git:
#        repo: https://github.com/dstanbeca/academyapp.git
#        dest: /home/ansible/repos/
#        clone: yes
#       version: main
#        force: yes
#        update: yes
    - name: Copy file from local to remote hosts
      copy: src=home/ansible/.ssh/id_ed25519 dest=home/ansible/.ssh/id_ed25519
    #  remote_src: yes
    #  become: yes
      
    #- name: Start ssh-agent on remote hosts
    #  command: 'eval "$(ssh-agent -s)"'
     
   # - name: Add ssh-key to ssh-agent
   #   command: ssh-add ~/.ssh/id_ed25519
      
    - name: Clone a private repository.
      git:
        repo: git@github.com:dstanbeca/academyapp.git
        version: main
        dest: /home/ansible/repos/
        accept_hostkey: yes
        key_file: /home/ansible/.ssh/id_ed25519
        clone: yes
        update: yes
        
    - name: Stop Docker Compose Stack running
      command: chdir=/home/ansible/repos/ docker compose down
      
    - name: Deploy Docker Compose stack
      command: chdir=/home/ansible/repos/ docker compose up -d
