---
    - name: Clone a github repository
      git:
        repo: https://github.com/dstanbeca/academyapp.git
        dest: /home/ansible/repos/
        clone: yes
        update: yes
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /home/ansible/repos/
        files:
        - docker-compose.yml
