---
    - name: Clone a private repository.
      git:
        repo: git@github.com:dstanbeca/academyapp.git
        version: 'v8.00'
        dest: /home/ansible/repos/
        accept_hostkey: yes
        force: yes
        clone: yes
        update: yes
        
    - name: Stop Docker Compose Stack running
      command: chdir=/home/ansible/repos/ docker compose down
      
    - name: Deploy Docker Compose stack
      command: chdir=/home/ansible/repos/ docker compose up -d
