---
- name: Update all packages
  vars:
   ansible_python_interpreter: /usr/bin/python2.7
  yum: name=* state=latest update_cache=true
  become: yes
  
- name: Disable SELinux
  vars:
   ansible_python_interpreter: /usr/bin/python2.7
  selinux: state=disabled
  become: yes

- name: Stop and disable firewalld.
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Set/Change system hostname
  hostname:
    name: "{{ inventory_hostname }}"
  
- name: Install NTP
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  become: yes
  yum: 
    name: ntp
    state: present
  
- name: Update date and time
  command: ntpdate time.apple.com
  become: yes
    
