---
- name: Update all packages
  vars:
   ansible_python_interpreter: /usr/bin/python2.7
  yum: name=* state=latest update_cache=true
  become: yes
  
- name: Disable SELinux
  selinux: state=disabled
  become: yes

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Set/Change system hostname
  hostname:
    name: "{{ inventory_hostname }}"
