---
- name: Update all packages
  yum: name=* state=latest update_cache=true

- name: Disable SELinux
  selinux: state=disabled

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Set/Change system hostname
  hostname:
    name: "{{ inventory_hostname }}"
