--- 
  - name: Update all packages
    yum: name=* state=latest update_cache=true
    become: yes
  
  - name: Disable SELinux
    selinux: state=disabled
    become: yes

  - name: Stop and disable firewalld.
    service:
      name: firewalld
      state: stopped
      enabled: False

  - name: Set/Change system hostname
    hostname:
      name: "{{ inventory_hostname }}"
  
  - name: Install NTP
    become: yes
    yum: 
      name: ntp
      state: present
  
  - name: Update date and time
    command: timedatectl set-timezone Europe/Athens && ntpdate time.apple.com
    become: yes
    
