- name: Example Registered Variables Conditionals
  hosts: all
  
  tasks:
  - name: Register an example variable
    shell: cat /etc/hostname
    register: hosts_contents

  - name: Check if hosts file contains the word "academy"
    debug:
      msg: "/etc/hostname file contains the word academy"
      when: hosts_contents.stdout.find("academy") != -1
      var: find_hosts_output